### ISSUE TITLE
C++ no longer has trigraphs

### ISSUE THREAD

**Issue by WesToleman** [glasnt/wat-references#3]
Hi Katie,

I saw the talk at YOW! last week and really enjoyed it. Are you aware that trigraphs are no longer in C++? They were deprecated in C++11 and removed in C++17. See [the linked wikipedia page](https://en.wikipedia.org/wiki/Digraphs_and_trigraphs#C++) and [CppReference](https://en.cppreference.com/w/cpp/language/operator_alternative#Trigraphs_.28removed_in_C.2B.2B17.29).

**Comment by glasnt** [comment]
Hello! Yes, I am aware of this one. My notes mention that this one is no longer an issue, but I apologise if in the YOW! '19 version of this talk I did not mention that.
